#!/bin/sh

# Copyright 2015-2017 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Unpacks files from archives of various types.
# For details run without arguments.

set -e

error() {
  echo >&2 "$(basename $0): error: $@"
  exit 1
}

warn() {
  echo >&2 "$(basename $0): warning: $@"
}

check_prog_silent() {
  which "$1" > /dev/null 2>&1
}

check_prog() {
  for p in "$@"; do
    if ! check_prog_silent "$p"; then
      error "your system is missing program '$p'" \
        "which is required to unpack this type of file"
    fi
  done
}

isemptydir() {
  test -d "$1" && test $(find "$1" -maxdepth 0 -empty)
}

strip_ext() {
  # Handle things like glibc-2.20.tar.bz2
  noext="${1%.*}"
  noext="${noext%.tar}"
  echo "$noext"
}

# Detect situations where it makes sense to unnest subfolder
# e.g. glibc-2.20/glibc-2.20
maybe_unnest() {
  d=$(ls -1 "$1")
  if [ $(echo "$d" | wc -l) -eq 1 -a "$d" = $(basename "$1") ]; then
    d=$(ls -1 "$1")
    mv $d $d.$$   # Workaround if some $f matches $d
    d="$d.$$"
    for f in $(ls -A "$1/$d"); do   # Respect hidden files
      mv "$1/$d/$f" "$1/$(basename $f)"
    done
    rmdir "$1/$d"
  fi
}

print_help_and_exit() {
  cat <<EOF
Syntax: $me FILE...
Unpacks archives of various types (based on extension of FILE).

Supported archives: .tar*, .zip, .jar, .apk, .7z, .rar, .deb, .rpm, .a, winmail.dat.

Example:
  $ pk my.tar.gz 1.txt 2.txt
  $ upk my.tar.gz
  $ ls my/
  1.txt 2.txt
EOF
  exit 1
}

me=$(basename $0)

curdir="$PWD"

test $# -eq 0 && print_help_and_exit

for src; do
  src=$(readlink -f "$src")
  src_no_ext=$(strip_ext $(basename "$src"))
  src_basename=$(basename $src)

  # Nest
  mkdir -p $src_no_ext
  if ! isemptydir "$src_no_ext"; then
    error "cowardly refusing to clear original contents of $src_no_ext"
  fi
  trap "cd $curdir && rm -rf $src_no_ext" EXIT
  cd $src_no_ext

  # Unpack
  case "$src_basename" in
    *.tar)
      check_prog tar
      tar xf "$src"
      ;;
    *.tar.gz | *.tgz)
      check_prog tar gunzip
      tar xzf "$src"
      ;;
    *.tar.bz2 | *.tbz2)
      check_prog tar bunzip2
      tar xjf "$src"
      ;;
    *.tar.xz | *.txz)
      check_prog tar unxz
      tar xJf "$src"
      ;;
#    *.gz)
#      gunzip "$src"
#      ;;
    *.zip | *.jar | *.apk)
      check_prog unzip
      unzip "$src"
      ;;
    *.7z)
      check_prog 7zr
      7zr x "$src"
      ;;
    *.rar)
      check_prog unrar
      unrar e "$src"
      ;;
    *.deb | *.ddeb)
      if check_prog_silent dpkg; then
        dpkg -x "$src" .
      elif check_prog_silent ar; then
        ar x "$src"
      else
        error "your system is missing programs 'dpkg' or 'ar'" \
          "which is required to unpack this type of file"
      fi
      ;;
    *.rpm)
      check_prog rpm2cpio
      rpm2cpio "$src" | cpio -id
      ;;
    *.a)
      check_prog ar
      ar x "$src"
      ;;
    winmail*.dat*)
      check_prog tnef
      tnef --file=$src
      ;;
    *)
      cd $curdir
      error "unsupported archive: $src"
      ;;
  esac

  maybe_unnest "$PWD"

  cd $curdir
  trap '' EXIT  # Unset
done

